//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: notes.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import Foundation
import Dispatch
import SwiftGRPC
import SwiftProtobuf

internal protocol NoteServiceListCall: ClientCallUnary {}

fileprivate final class NoteServiceListCallBase: ClientCallUnaryBase<Empty, NoteList>, NoteServiceListCall {
  override class var method: String { return "/BuilderService/List" }
}

/// Instantiate NoteServiceServiceClient, then call methods of this protocol to make API calls.
internal protocol NoteServiceService: ServiceClient {
  /// Synchronous. Unary.
  func list(_ request: Empty) throws -> NoteList
  /// Asynchronous. Unary.
  func list(_ request: Empty, completion: @escaping (NoteList?, CallResult) -> Void) throws -> NoteServiceListCall

}

internal final class NoteServiceServiceClient: ServiceClientBase, NoteServiceService {
  /// Synchronous. Unary.
  internal func list(_ request: Empty) throws -> NoteList {
    return try NoteServiceListCallBase(channel)
      .run(request: request, metadata: metadata)
  }
  /// Asynchronous. Unary.
  internal func list(_ request: Empty, completion: @escaping (NoteList?, CallResult) -> Void) throws -> NoteServiceListCall {
    return try NoteServiceListCallBase(channel)
      .start(request: request, metadata: metadata, completion: completion)
  }

 
}

